// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosSystem.Main.Database;

#nullable disable

namespace PosSystem.Main.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("PosSystem.Main.Models.Account", b =>
                {
                    b.Property<int>("AccID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccPass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccID");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccID = 1,
                            AccName = "Admin",
                            AccPass = "123",
                            AccRole = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            AccID = 2,
                            AccName = "Nhân viên 1",
                            AccPass = "123",
                            AccRole = "Staff",
                            Username = "nv1"
                        });
                });

            modelBuilder.Entity("PosSystem.Main.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Cà phê",
                            OrderIndex = 1
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Sinh tố & Nước ép",
                            OrderIndex = 2
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Đồ ăn vặt",
                            OrderIndex = 3
                        });
                });

            modelBuilder.Entity("PosSystem.Main.Models.Dish", b =>
                {
                    b.Property<int>("DishID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DishStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DishType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DishID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishID = 1,
                            CategoryID = 1,
                            DishName = "Cà phê đen",
                            DishStatus = "Active",
                            DishType = "Food",
                            ImagePath = "cfden.png",
                            Price = 20000m,
                            Unit = "Ly"
                        },
                        new
                        {
                            DishID = 2,
                            CategoryID = 1,
                            DishName = "Cà phê sữa",
                            DishStatus = "Active",
                            DishType = "Food",
                            ImagePath = "cfsua.png",
                            Price = 25000m,
                            Unit = "Ly"
                        },
                        new
                        {
                            DishID = 3,
                            CategoryID = 2,
                            DishName = "Sinh tố bơ",
                            DishStatus = "Active",
                            DishType = "Drink",
                            ImagePath = "stbo.png",
                            Price = 40000m,
                            Unit = "Ly"
                        },
                        new
                        {
                            DishID = 4,
                            CategoryID = 3,
                            DishName = "Khoai tây chiên",
                            DishStatus = "Active",
                            DishType = "Food",
                            ImagePath = "khoaitay.png",
                            Price = 30000m,
                            Unit = "Dĩa"
                        });
                });

            modelBuilder.Entity("PosSystem.Main.Models.Order", b =>
                {
                    b.Property<long>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TableID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.HasIndex("AccID");

                    b.HasIndex("TableID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PosSystem.Main.Models.OrderDetail", b =>
                {
                    b.Property<long>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DishID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("DishID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PosSystem.Main.Models.PrintTemplate", b =>
                {
                    b.Property<int>("TemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LayoutConfig")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaperSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TemplateID");

                    b.ToTable("PrintTemplate");

                    b.HasData(
                        new
                        {
                            TemplateID = 1,
                            IsActive = true,
                            LayoutConfig = "\r\n        {\r\n            \"Header\": {\r\n                \"ShowLogo\": true,\r\n                \"ShopNameSize\": 14,\r\n                \"AddressSize\": 10\r\n            },\r\n            \"Body\": {\r\n                \"ShowNo\": true,\r\n                \"ShowPrice\": true\r\n            },\r\n            \"Footer\": {\r\n                \"ShowWifi\": true,\r\n                \"ShowQr\": true,\r\n                \"EndMessage\": \"Xin cảm ơn và hẹn gặp lại!\"\r\n            }\r\n        }",
                            PaperSize = 80,
                            TemplateName = "Mẫu Hóa Đơn Chuẩn (80mm)",
                            TemplateType = "Bill"
                        },
                        new
                        {
                            TemplateID = 2,
                            IsActive = true,
                            LayoutConfig = "{ \"Header\": { \"ShowShopName\": false }, \"Body\": { \"FontSize\": 14 } }",
                            PaperSize = 80,
                            TemplateName = "Mẫu Bếp (Rút gọn)",
                            TemplateType = "Kitchen"
                        });
                });

            modelBuilder.Entity("PosSystem.Main.Models.Table", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TableID");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableID = 1,
                            TableName = "Bàn 1",
                            TableStatus = "Empty",
                            TableType = "DineIn"
                        },
                        new
                        {
                            TableID = 2,
                            TableName = "Bàn 2",
                            TableStatus = "Empty",
                            TableType = "DineIn"
                        });
                });

            modelBuilder.Entity("PosSystem.Main.Models.Dish", b =>
                {
                    b.HasOne("PosSystem.Main.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PosSystem.Main.Models.Order", b =>
                {
                    b.HasOne("PosSystem.Main.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccID");

                    b.HasOne("PosSystem.Main.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableID");

                    b.Navigation("Account");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("PosSystem.Main.Models.OrderDetail", b =>
                {
                    b.HasOne("PosSystem.Main.Models.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PosSystem.Main.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PosSystem.Main.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
